api_login_check:
  path: /api/login

api_secured:
  path:       /api/secured
  controller: App\Controller\ApiController::securedAction
  methods:    GET

api_unsecured:
  path:       /api/unsecured
  controller: App\Controller\ApiController::unsecuredAction
  methods:    GET
  
web_secured_1:
  path:       /web/secured-1
  controller: App\Controller\WebController::securedOneAction
  methods:    GET

web_secured_2:
  path:       /web/secured-2
  controller: App\Controller\WebController::securedTwoAction
  methods:    GET

web_unsecured:
  path:       /web/unsecured
  controller: App\Controller\WebController::unsecuredAction
  methods:    GET

web_index:
  path:       /web
  controller: App\Controller\WebController::indexAction
  methods:    GET

web_login_check:
  path:       /web/login
  controller: App\Controller\WebController::loginAction
  methods:    [GET, POST]